server:
    address1: 192.168.1.100
    tomcat:
      basedir: tomcat-log
      accesslog:
        enabled: true
        pattern: "%t %a \"%r\" %s (%D ms)"
#debug: true
logging:
  file: spring.log
spring:
   datasource:
        url: jdbc:mysql://localhost/springboot?useSSL=false
        username: root
        password: wanghj123
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/domain/**/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
---
spring:
    profiles: development
debug: true
logging:
  file: spring.log
  level:
    web:
      debug:true
server:
    address1: 127.0.0.1
---
spring:
    profiles: production & eu-central
server:
    address1: 192.168.1.120