server:
    address1: 192.168.1.100
#debug: true
logging:
  file: spring.log
spring:
   datasource:
        url: jdbc:mysql://localhost/springboot?useSSL=false
        username: root
        password: wanghj123
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/domain/**/*.xml
---
spring:
    profiles: development
debug: true
logging:
  file: spring.log
  level:
    web:
      debug:true
server:
    address1: 127.0.0.1
---
spring:
    profiles: production & eu-central
server:
    address1: 192.168.1.120