#debug: true
#logging:
#  file: spring.log
spring:
   datasource:
        url: jdbc:mysql://localhost/springboot?useSSL=false
        username: root
        password: wanghj123
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:hello/domain/**/*.xml
mybatis-plus:
  type-aliases-package: classpath:hello.domain
  check-config-location: true
---
spring:
    profiles: development
debug: true
logging:
  file: spring.log
  level:
    web:
      debug:true
---
spring:
    profiles: production & eu-central